version: "3.4"

services:
  teleferic:
    build:
      context: ./teleferic/
      args:
        - PORT=8000
    image: 'peer-mountain01:5005/teleferic-mvp/teleferic:${TAG:-latest}'
    environment:
      - ENVIRONMENT=PRODUCTION
      - AUTHORIZER_ENDPOINT_HOSTNAME=authorizer
      - AUTHORIZER_ENDPOINT_PORT=8000
      - GRAPHIQL=TRUE
      - PORT=8000
    networks:
      - teleferic
      - authorizer

    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
      restart_policy:
          condition: "on-failure"

  nginx:
    build:
      context: ./nginx
    image: 'peer-mountain01:5005/teleferic-mvp/nginx:${TAG:-latest}'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 8000:8000
      - 4443:4443
    networks:
      - teleferic

    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
      restart_policy:
          condition: "on-failure"
      placement:
        constraints:
          - node.role == manager


networks:
  teleferic:
    external: true
  authorizer:
    external: true
